FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install -g @angular/cli

RUN npm ci

COPY . .

RUN ng build --configuration production

RUN ls -la /app/dist/

FROM nginx:alpine

COPY --from=build /app/dist/browser/ /usr/share/nginx/html/

EXPOSE 80